config/routes.rb
TrafficCardSystem::Application.routes.draw do
	match 'trans_logs/' => 'TransLog#index'
	match 'transfer_logs/' => 'TransferLog#index'
	match 'error_logs/' => 'ErrorLog#index'
	match 'trans_logs/statistic' => 'TransLog#statistic'
	match 'transfer_logs/statistic' => 'TransferLog#statistic'
	match 'error_logs/statistic' => 'ErrorLog#statistic'

end

app/models/error_log.rb
class ErrorLog < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/trans_log.rb
class TransLog < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/transfer_log.rb
class TransferLog < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/error_log_controller.rb
class ErrorLogController < ApplicationController
	layout 'producers'
	def index
		@error_logs = ErrorLog.all

		respond_to do |format|
			format.html #index.html.erb
			format.json { render json: @error_logs }
		end
	end
end

app/controllers/trans_log_controller.rb
class TransLogController < ApplicationController

	layout 'producers'
	def index
		@trans_logs = TransLog.all

		respond_to do |format|
			format.html # index.html.erb
			format.json { render json: @trans_logs }
		end
	end

	def statistic
		@trans_logs = TransLog.all
		@total_cost = Array.new(5) { Array.new(3) }
		@total_cost[0][0] = 5513
		@total_cost[0][1] = 0
		@total_cost[0][2] = 0 
		@total_cost[1][0] = 5516
		@total_cost[1][1] = 0
		@total_cost[1][2] = 0
		@_total_cost = 0
		@_total_discounted_cost =0

		@trans_logs.each do |log|
			if log.busRouteNm == 5513
				@total_cost[0][2] += log.cost
				@total_cost[0][1] += log.discountedCost
			elsif log.busRouteNm == 5516
				@total_cost[1][2] += log.cost
				@total_cost[1][1] += log.discountedCost
			end
			@_total_cost += log.cost
			@_total_discounted_cost += log.discountedCost
		end

		respond_to do |format|
			format.html #statistic.html.erb
			format.json { render json: @trans_logs }
		end
	end
end

app/controllers/transfer_log_controller.rb
class TransferLogController < ApplicationController
	layout 'producers'
	def index
		@transfer_logs = TransferLog.all	
		respond_to do |format|
			format.html #index.html.erb
			format.json { render json: @trans_logs }
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_log_helper.rb
module ErrorLogHelper
end

app/helpers/trans_log_helper.rb
module TransLogHelper
end

app/helpers/transfer_log_helper.rb
module TransferLogHelper
end

app/views/error_log/index.html.erb
<div class = "title">
	<h1> Error Log </h1>
	<%= link_to 'Statistic', error_logs_statistic_path %>
</div>
<table class="table table-striped">
	<tr>
		<th>Card ID</th>
		<th>Error Occured Time</th>
		<th>Error Message</th>
	</tr>

<% @error_logs.each do |log| %>
	<tr>
		<td><%= log.cardID %></td>
		<td><%= log.errorOccurTime %></td>
		<td><%= log.errorMessage %></td>
	</tr>
<% end %>
</table>

<br />

app/views/error_log/statistic.html.erb
<div class="title">
	<h1> Statistic </h1>
	<%= link_to 'Back to Log', error_logs_path %>
</div>

app/views/layouts/_header.html.erb
<!--
<ul class="nav nav-tabs">
	<li class="active">
	<%= link_to "정산담당자", trans_logs_path %>
	</li>
	<li>
	<%= link_to "승객", trans_logs_path %>
	</li>
</ul>
-->
<div class="navbar navbar-inverse navbar-fixed-top">
	<div class="navbar-inner">
 	<div class="container">
		<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
			<span class = "icon-bar"></span>
			<span class = "icon-bar"></span>
			<span class = "icon-bar"></span>
		</a>
		<a class="brand" href="#"> Traffic Card System </a>
			<div class="nav-collapse">
			<ul class="nav">
				<li><%= link_to "정산담당자", trans_logs_path %></li>
				<li><%= link_to "승객", trans_logs_path %></li>
			</ul>
		</div>
	</div>
	</div>
</div>

app/views/layouts/_menu_for_producers.html.erb
<div class="tabbable tabs-left">
	<ul class="nav nav-tabs">
		<li class="active"> <%= link_to 'Transit Log', trans_logs_path %> </li>
		<li> <%= link_to 'Transfer Log', transfer_logs_path %> </li>
		<li> <%= link_to 'Error Log', error_logs_path %></li>
	</ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TrafficCardSystem</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

</head>

<body>

<div class = "row">

<div class="span2">
	<%= link_to 'Transit Log', trans_logs_path %>
	<br/>
	<%= link_to 'Transfer Log', transfer_logs_path %>
	<br/>
	<%= link_to 'Error Log', error_logs_path %>
</div>

<div class = "span10">
<%= yield %>
</div>

</div>

</body>
</html>

app/views/layouts/consumers.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TrafficCardSystem</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
<link rel="style" type="text/css" href="style.css"/>
</head>

<body>

<%= render :partial => "layouts/header" %>

<%= render :partial => "layouts/menu_for_producers" %>

<div class = "span10">
	<%= yield %>
</div>

</div>

</body>
</html>

app/views/layouts/producers.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TrafficCardSystem</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>

<%= render :partial => "layouts/header" %>

<div class = "row">
	<div class = "span2">
		<%= render :partial => "layouts/menu_for_producers" %>
	</div>

	<div class = "span10">
		<%= yield %>
	</div>
</div>


</body>
</html>

app/views/trans_log/index.html.erb
<div class = "title">
	<h1 class="Title">Transit Logs</h1>
	<%= link_to 'Statistic', trans_logs_statistic_path %>  
</div>
<table class="table table-striped">
	<tr>
		<th>Card ID</th>
		<th>Bus Number</th>
		<th>Boarding Time</th>
		<th>Boarding Place</th>
		<th>Landing Time</th>
		<th>Landing Place</th>
		<th>Cost</th>
		<th>Discounted Cost</th>
	</tr>

<% @trans_logs.each do |log| %>
	<tr>
		<td><%= log.cardID %></td>
		<td><%= log.busRouteNm %></td>
		<td><%= log.boardingTime %></td>
		<td><%= log.boardingPlace %></td>
		<td><%= log.landingTime %></td>
		<td><%= log.landingPlace %></td>
		<td><%= log.cost %></td>
		<td><%= log.discountedCost %></td>
	</tr>
<% end %>
</table>

<br />

app/views/trans_log/statistic.html.erb
<div class = "title">
	<h1> statistic </h1>
	<%= link_to 'Back to Log', trans_logs_path %>
</div>

<h4> 버스 노선당 사용금액 </h4>
<table class="table table-striped">
	<tr>
		<th>버스노선번호</th>
		<th>총 사용액</th>
		<th>실 사용액</th>
		<th>버스노선번호</th>
		<th>총 사용액</th>
		<th>실 사용액</th>
		<th>버스노선번호</th>
		<th>총 사용액</th>
		<th>실 사용액</th>
	</tr>
	
	<tr>
		<td><%= @total_cost[0][0] %></td>
		<td><%= @total_cost[0][1] %></td>
		<td><%= @total_cost[0][2] %></td>
		<td><%= @total_cost[1][0] %></td>
		<td><%= @total_cost[1][1] %></td>
		<td><%= @total_cost[1][2] %></td>
	</tr>
</table>

<h4> 총 버스이용금액 <h4>
<%= @_total_cost %>
<%= @_total_discounted_cost %>

app/views/transfer_log/index.html.erb
<link rel="style" type="text/css" href="style.css"/>

<div class="title">
	<h1 class="Title"> Transfer Log </h1>
	<%= link_to 'Statistic', transfer_logs_statistic_path %>
</div>
<table class="table table-striped">
<div id=transfersubject">
<tr>
		<th>Card ID</th>
		<th>Transfer Time</th>
		<th>Transfer From</th>
		<th>Transfer To </th>
		<th>Discounted Cost</th>
	</tr>
</div>
<div id=transfercontents>
<% @transfer_logs.each do |log| %>
	<% @transferFrom = TransLog.find(log.transferFrom) %>
	<% @transferTo = TransLog.find(log.transferTo) %>
	<tr>
		<td><%= log.cardID %></td>
		<td><%= @transferTo.boardingTime %></td>
		<td><%= @transferFrom.busRouteNm %></td>
		<td><%= @transferTo.busRouteNm %></td>
		<td><%= @transferTo.discountedCost %></td>
	</tr>
</div>
<% end %>
</table>

<br />

app/views/transfer_log/statistic.html.erb
<div class="title">
	<h1> Statistic </h1>
	<%= link_to 'Back to Log', transfer_logs_path %>
</div>